services:
  nginx:
    image: nginx:alpine
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - .:/app
      - ./docker/nginx/nginx-swarm.conf:/etc/nginx/conf.d/default.conf
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.greatfood-http.rule=Host(`greatfood.docker.localhost`)
        - traefik.http.routers.greatfood-http.entrypoints=http
        - traefik.http.services.greatfood.loadbalancer.server.port=80
    depends_on:
      - php
    networks:
      - traefik-public
      - app

  php:
    image: greatfood-php
    env_file:
      - .env
    networks:
      - app
    volumes:
      - .:/app
      - vendor_data:/app/vendor

networks:
  app:
  traefik-public:
    external: true

configs:
  nginx_conf:
    file: ./docker/nginx/nginx-swarm.conf

volumes:
  vendor_data:
